### ISSUE TITLE
Error using git clone

### ISSUE THREAD

**Issue by rishibhandari63** [bioinf-mcb/metagenome_assembly#5]
git clone www.github.com/crusher083/metagenome_assembly
fatal: repository 'www.github.com/crusher083/metagenome_assembly' does not exist

**Comment by valentynbez** [comment]
Hello, thanks for the issue! 
It was my private repo for a long time and I deanonymised my github profile since. I updated a readme (commit 30985d6)
Although be cautious, this pipeline was specifically tailored for the infrastructure we used at the moment, and we cannot guarantee it will work in yours. However, I will try to provide adequate assistance. 

Cheers, 
Valentyn
